//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGameRpg.Engine.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGameRpg.Engine.Resources.Languages.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue . . ..
        /// </summary>
        internal static string Intro_PressAnyKey {
            get {
                return ResourceManager.GetString("Intro_PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +20 HP.
        /// </summary>
        internal static string LegendView_1Life {
            get {
                return ResourceManager.GetString("LegendView_1Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1 point.
        /// </summary>
        internal static string LegendView_1Point {
            get {
                return ResourceManager.GetString("LegendView_1Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2 points.
        /// </summary>
        internal static string LegendView_2Points {
            get {
                return ResourceManager.GetString("LegendView_2Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +3 points.
        /// </summary>
        internal static string LegendView_3Points {
            get {
                return ResourceManager.GetString("LegendView_3Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagger.
        /// </summary>
        internal static string LegendView_Dagger {
            get {
                return ResourceManager.GetString("LegendView_Dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        internal static string LegendView_Friend {
            get {
                return ResourceManager.GetString("LegendView_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        internal static string LegendView_Hammer {
            get {
                return ResourceManager.GetString("LegendView_Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonuses.
        /// </summary>
        internal static string LegendView_Header_Bonuses {
            get {
                return ResourceManager.GetString("LegendView_Header_Bonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous objects.
        /// </summary>
        internal static string LegendView_Header_DangerousObjects {
            get {
                return ResourceManager.GetString("LegendView_Header_DangerousObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructible obstacles.
        /// </summary>
        internal static string LegendView_Header_DestructibleObstacles {
            get {
                return ResourceManager.GetString("LegendView_Header_DestructibleObstacles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indestructible obstacles.
        /// </summary>
        internal static string LegendView_Header_IndestructibleObstacles {
            get {
                return ResourceManager.GetString("LegendView_Header_IndestructibleObstacles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string LegendView_Header_Items {
            get {
                return ResourceManager.GetString("LegendView_Header_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string LegendView_Header_Navigation {
            get {
                return ResourceManager.GetString("LegendView_Header_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string LegendView_Header_Persons {
            get {
                return ResourceManager.GetString("LegendView_Header_Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string LegendView_Header_Weapon {
            get {
                return ResourceManager.GetString("LegendView_Header_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostile.
        /// </summary>
        internal static string LegendView_Hostile {
            get {
                return ResourceManager.GetString("LegendView_Hostile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mighty hammer.
        /// </summary>
        internal static string LegendView_MightyHammer {
            get {
                return ResourceManager.GetString("LegendView_MightyHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movable crate.
        /// </summary>
        internal static string LegendView_MovableCrate {
            get {
                return ResourceManager.GetString("LegendView_MovableCrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string LegendView_Player {
            get {
                return ResourceManager.GetString("LegendView_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sledgehammer.
        /// </summary>
        internal static string LegendView_Sledgehammer {
            get {
                return ResourceManager.GetString("LegendView_Sledgehammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap.
        /// </summary>
        internal static string LegendView_Trap {
            get {
                return ResourceManager.GetString("LegendView_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turret.
        /// </summary>
        internal static string LegendView_Turret {
            get {
                return ResourceManager.GetString("LegendView_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string LegendView_Wall {
            get {
                return ResourceManager.GetString("LegendView_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cracked wall.
        /// </summary>
        internal static string LegendView_Wall2 {
            get {
                return ResourceManager.GetString("LegendView_Wall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сrumbling wall.
        /// </summary>
        internal static string LegendView_Wall3 {
            get {
                return ResourceManager.GetString("LegendView_Wall3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragile wall.
        /// </summary>
        internal static string LegendView_Wall4 {
            get {
                return ResourceManager.GetString("LegendView_Wall4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way sign.
        /// </summary>
        internal static string LegendView_WaySign {
            get {
                return ResourceManager.GetString("LegendView_WaySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string LegendView_Web {
            get {
                return ResourceManager.GetString("LegendView_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 5.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 6.
        /// </summary>
        internal static string Level6 {
            get {
                return ResourceManager.GetString("Level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This console application created as a pet-project by Sergey V. For informational purposes only. .
        /// </summary>
        internal static string MainMenu_Credits {
            get {
                return ResourceManager.GetString("MainMenu_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit? Enter - yes | Esc - no.
        /// </summary>
        internal static string MainMenu_ExitQuestion {
            get {
                return ResourceManager.GetString("MainMenu_ExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainMenu_Settings {
            get {
                return ResourceManager.GetString("MainMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        internal static string MainMenu_StartGame {
            get {
                return ResourceManager.GetString("MainMenu_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: in order to control menu  use buttons W↑ and S↓.
        /// </summary>
        internal static string MainMenu_Tip1 {
            get {
                return ResourceManager.GetString("MainMenu_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make choice press Enter.
        /// </summary>
        internal static string MainMenu_Tip2 {
            get {
                return ResourceManager.GetString("MainMenu_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To go back press Escape.
        /// </summary>
        internal static string MainMenu_Tip3 {
            get {
                return ResourceManager.GetString("MainMenu_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to main menu.
        /// </summary>
        internal static string PauseMenu_ExitToMainMenu {
            get {
                return ResourceManager.GetString("PauseMenu_ExitToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds: disabled.
        /// </summary>
        internal static string SettingsMenu_Music_Off {
            get {
                return ResourceManager.GetString("SettingsMenu_Music_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds: enabled.
        /// </summary>
        internal static string SettingsMenu_Sounds_On {
            get {
                return ResourceManager.GetString("SettingsMenu_Sounds_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language interface.
        /// </summary>
        internal static string SettingsMenu_UILang {
            get {
                return ResourceManager.GetString("SettingsMenu_UILang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string SettingsMenu_UILang_En {
            get {
                return ResourceManager.GetString("SettingsMenu_UILang_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string SettingsMenu_UILang_Ru {
            get {
                return ResourceManager.GetString("SettingsMenu_UILang_Ru", resourceCulture);
            }
        }
    }
}
