//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGameRpg.Engine.Resources.Paths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGameRpg.Engine.Resources.Paths.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/intro/intro.txt.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/levels/level1.txt.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/levelsMenu/levelsMenuHeaderEng.txt.
        /// </summary>
        internal static string LevelsMenuHeaderEng {
            get {
                return ResourceManager.GetString("LevelsMenuHeaderEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/levelsMenu/levelsMenuHeaderRus.txt.
        /// </summary>
        internal static string LevelsMenuHeaderRus {
            get {
                return ResourceManager.GetString("LevelsMenuHeaderRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/mainMenu/mainMenuHeader.txt.
        /// </summary>
        internal static string MainMenuHeader {
            get {
                return ResourceManager.GetString("MainMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/mainMenu/mainMenuTip.txt.
        /// </summary>
        internal static string MainMenuTip {
            get {
                return ResourceManager.GetString("MainMenuTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/pauseMenu/pauseMenuHeaderEng.txt.
        /// </summary>
        internal static string PauseMenuHeaderEng {
            get {
                return ResourceManager.GetString("PauseMenuHeaderEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/pauseMenu/pauseMenuHeaderRus.txt.
        /// </summary>
        internal static string PauseMenuHeaderRus {
            get {
                return ResourceManager.GetString("PauseMenuHeaderRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/settingsMenu/settingsHeaderEng.txt.
        /// </summary>
        internal static string SettingsMenuHeaderEng {
            get {
                return ResourceManager.GetString("SettingsMenuHeaderEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../../Engine/Resources/GraphicElements/settingsMenu/settingsHeaderRus.txt.
        /// </summary>
        internal static string SettingsMenuHeaderRus {
            get {
                return ResourceManager.GetString("SettingsMenuHeaderRus", resourceCulture);
            }
        }
    }
}
